name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Run tests
      run: go test -v ./...

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Check formatting
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "Please run 'go fmt ./...'"
          gofmt -d .
          exit 1
        fi

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.5.0
        args: --timeout=5m

  demo-test:
    runs-on: ubuntu-latest
    needs: [test, format, lint]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl

        # Install Ollama
        curl -fsSL https://ollama.com/install.sh | sh

        # Wait for Ollama to be ready
        echo "Waiting for Ollama to start..."
        for i in {1..30}; do
          if curl -s http://localhost:11434/api/version >/dev/null 2>&1; then
            echo "Ollama is ready"
            break
          fi
          sleep 2
        done
        
        # Install Keto
        curl -L https://github.com/ory/keto/releases/download/v0.12.0/keto_0.12.0-linux_64bit.tar.gz | tar xz
        sudo mv keto /usr/local/bin/

    - name: Cache Ollama models
      uses: actions/cache@v4
      with:
        path: ~/.ollama
        key: ollama-models-${{ runner.os }}-llama32-1b-nomic
        restore-keys: |
          ollama-models-${{ runner.os }}-

    - name: Start Ollama and pull models
      run: |
        # Pull models (will use cache if available)
        ollama pull nomic-embed-text
        ollama pull llama3.2:1b

    - name: Build application
      run: go build -o rerag-rbac-rag-llm .

    - name: Run demo test
      run: |
        # Start services
        keto serve --config keto/config.yml &
        KETO_PID=$!

        ./rerag-rbac-rag-llm &
        APP_PID=$!
        
        keto namespace migrate up --config keto/config.yml

        # Wait for app to be ready
        echo "Waiting for application to start..."
        for i in {1..30}; do
          if curl -s http://localhost:4467/health >/dev/null 2>&1; then
            echo "Application is ready"
            break
          fi
          sleep 1
        done
        for i in {1..30}; do
          if curl -s http://localhost:4477/health >/dev/null 2>&1; then
            echo "Application is ready"
            break
          fi
          sleep 1
        done

        # Setup and run demo
        ./scripts/setup-keto-permissions.sh
        ./scripts/load_documents.sh

        # Run demo
        make demo

        # Cleanup
        kill $APP_PID $KETO_PID 2>/dev/null || true